name: Daily Commit at 22f3000713@ds.study.iitm.ac.in

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository at 22f3000713@ds.study.iitm.ac.in
        uses: actions/checkout@v4

      - name: Commit and push changes at 22f3000713@ds.study.iitm.ac.in
        run: |
          git config --local user.email "22f3000713@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git add test.json
          git commit -m "Update Daily Commute 22f3000713@ds.study.iitm.ac.in" || exit 0
          git push
